### ISSUE TITLE
Add screenshots?

### ISSUE THREAD

**Issue by Gys** [ankorstore/yokai-showroom#5]
Hi!

I had a quick look around and found this demo: https://github.com/ankorstore/yokai-showroom/tree/main/http-demo

It refers to:

    After a short moment, the application will offer:
        http://localhost:8080/: application dashboard
        http://localhost:8081/: application core dashboard

So I understand it shows a HTML page?  In which case a screenshot would be very helpful, to get some idea what is generated out of the box.

**Comment by Gys** [comment]
> Not sure it's useful though to screen shot the dashboard of the demo app, since users can just click to open it (and it's a demo app that may change, I plan to add more things in a short future)

You mean there is an online demo app? I did not see anything like that and for that reason I suggested the screenshots. What is the link to the online demo app?

**Comment by ekkinox** [comment]
I meant that once you run the docker compose stack, and open http://localhost:8080, the demo app dashboard, you have a very simple html page listing available endpoints of the crud API. It's just here as example for using html templates with Yokai.

Not sure this deserves a screenshot, users can just click and go see.

But a screenshot of the core dashboard is already available in Yokai docs, so I'll follow your idea and link to the docs 👍
